stderr of test 'crash_on_concurrent_use.SF-1411926` in directory 'sql/test/concurrent` itself:


# 11:36:09 >  
# 11:36:09 >   Mserver "--config=/ufs/niels/scratch/monetdb/Linux-x86_64/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/ufs/niels/scratch/monetdb/Linux-x86_64/lib/MonetDB4:/ufs/niels/scratch/monetdb/Linux-x86_64/lib/MonetDB4/lib:/ufs/niels/scratch/monetdb/Linux-x86_64/lib/MonetDB4/bin" --set "gdk_dbfarm=/ufs/niels/scratch/monetdb/Linux-x86_64/var/MonetDB4/dbfarm" --set "sql_logdir=/ufs/niels/scratch/monetdb/Linux-x86_64/var/MonetDB4/sql_logs" --set "xquery_logdir=/ufs/niels/scratch/monetdb/Linux-x86_64/var/MonetDB4/xquery_logs" --set mapi_open=true --set xrpc_open=true --set mapi_port=31284 --set xrpc_port=47959 --set monet_prompt= --trace "--dbname=mTests_src_test_concurrent" "--dbinit= module(sql_server);" ; echo ; echo Over..
# 11:36:09 >  


# 11:36:09 >  
# 11:36:09 >  /usr/bin/python crash_on_concurrent_use.SF-1411926.SQL.py crash_on_concurrent_use.SF-1411926 
# 11:36:09 >  


# 11:36:09 >  
# 11:36:09 >  Done.
# 11:36:09 >  

