#propagate INT exception
function foo();
raise	IllegalAccess := 1234;
	io.print("should not come here\n");
catch IllegalAccess;
	io.printf("caught %d\n",IllegalAccess);
exit IllegalAccess;
end;
foo();
