stderr of test 'wlr110` in directory 'sql/test/wlcr` itself:


# 21:18:11 >  
# 21:18:11 >  "/usr/bin/python3" "wlr110.py" "wlr110"
# 21:18:11 >  

# builtin opt 	gdk_dbpath = /export/scratch1/mk/branches/tracer//Linux/var/monetdb5/dbfarm/demo
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_ipv6 = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# builtin opt 	raw_strings = false
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 48379
# cmdline opt 	mapi_usock = /var/tmp/mtest-26983/.s.monetdb.48379
# cmdline opt 	gdk_dbpath = /export/scratch1/mk/branches/tracer//Linux/var/MonetDB/mTests_sql_test_wlcrclone
MAPI  = (monetdb) /var/tmp/mtest-26983/.s.monetdb.48379
QUERY = call wlr.replicate('halo');
ERROR = !Timestamp (halo) has incorrect format
CODE  = 22007

# 21:18:12 >  
# 21:18:12 >  "Done."
# 21:18:12 >  

