stderr of test 'msqldump-mapi-cache.Bug-6777` in directory 'sql/test/BugTracker-2019` itself:


# 11:52:10 >  
# 11:52:10 >  "/usr/bin/python3" "msqldump-mapi-cache.Bug-6777.py" "msqldump-mapi-cache.Bug-6777"
# 11:52:10 >  

# builtin opt 	gdk_dbpath = /home/ferreira/repositories/MonetDB-Nov2019/BUILD/var/monetdb5/dbfarm/demo
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_ipv6 = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 39556
# cmdline opt 	mapi_usock = /var/tmp/mtest-4558/.s.monetdb.39556
# cmdline opt 	gdk_dbpath = /home/ferreira/repositories/MonetDB-Nov2019/BUILD/var/MonetDB/mTests_sql_test_BugTracker-2019

# 11:52:37 >  
# 11:52:37 >  "Done."
# 11:52:37 >  

