stderr of test 'error-clean-cache.Bug-6351` in directory 'sql/test/BugTracker-2017` itself:


# 15:10:19 >  
# 15:10:19 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=36136" "--set" "mapi_usock=/var/tmp/mtest-222580/.s.monetdb.36136" "--forcemito" "--dbpath=/home/ferreira/repositories/MonetDB-Nov2019/BUILD/var/MonetDB/mTests_sql_test_BugTracker-2017" "--set" "embedded_r=yes" "--set" "embedded_py=2" "--set" "embedded_c=true"
# 15:10:19 >  

# builtin opt 	gdk_dbpath = /home/ferreira/repositories/MonetDB-Nov2019/BUILD/var/monetdb5/dbfarm/demo
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_ipv6 = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 36136
# cmdline opt 	mapi_usock = /var/tmp/mtest-222580/.s.monetdb.36136
# cmdline opt 	gdk_dbpath = /home/ferreira/repositories/MonetDB-Nov2019/BUILD/var/MonetDB/mTests_sql_test_BugTracker-2017
# cmdline opt 	embedded_r = yes
# cmdline opt 	embedded_py = 2
# cmdline opt 	embedded_c = true
#client2:!ERROR:ParseException:SQLparser:42000!syntax error, unexpected IDENT in: "iamerror"
#client2:!ERROR:ParseException:SQLparser:42000!SELECT: identifier 'a' unknown

# 15:10:20 >  
# 15:10:20 >  "mclient" "-lsql" "-ftest" "-tnone" "-Eutf-8" "-i" "-e" "--host=/var/tmp/mtest-222580" "--port=36136"
# 15:10:20 >  

MAPI  = (monetdb) /var/tmp/mtest-222580/.s.monetdb.36136
QUERY = iamerror; --just an error
ERROR = !syntax error, unexpected IDENT in: "iamerror"
CODE  = 42000

# 15:10:20 >  
# 15:10:20 >  "Done."
# 15:10:20 >  

